import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const zenKurenaido = localFont({
  src: "./fonts/ZenKurenaido-Regular.ttf",
  variable: "--font-zen-kurenaido",
  display: "swap",
});

const amaticSC = localFont({
  src: "./fonts/AmaticSC-Regular.ttf",
  variable: "--font-amatic-sc",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${zenKurenaido.variable} ${amaticSC.variable} h-full antialiased`}
    >
      <body className={`${zenKurenaido.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
